- name: Grindstone timer
  identifier:
    kind: exe
    id: GS4.exe
  options:
    - tray_and_multi_window
- name: workrave
  identifier:
    kind: exe
    id: workrave.exe
  float_identifiers:
  - kind: title
    id: Workrave
    comment: Targets the floating timer
  - kind: title
    id: Exercises
  - kind: title
    id: Rest break
  - kind: title
    id: Micro-break
  options:
    - tray_and_multi_window
- name: hunt and peck
  identifier:
    kind: exe
    id: hap.exe
  options:
    - tray_and_multi_window
- name: VSCodium
  identifier:
    kind: Exe
    id: codium.exe
  options:
  - border_overflow
- name: Vieb browser
  identifier:
    kind: Exe
    id: Vieb.exe
  options:
  - border_overflow
