#!/bin/bash
cd $HOME
XDG_CONFIG_HOME="$HOME/.config"
export DOTFILES_DIR=$(cat "${XDG_CONFIG_HOME}/.dotfiles_dir")
export YABAI_CONFIG_DIR="$DOTFILES_DIR/windowManagers/yabai"
. "$YABAI_CONFIG_DIR/../variables.sh"

# Inconsistent treatment of skhd vs limelight...
if ! pgrep skhd; then
  skhd >> $HOME/.logs/skhd.log 2>> $HOME/.logs/skhd.err &
fi
# kill any existing limelight process if one exists, before we launch a new one
killall limelight &> /dev/null
PATH="$PATH:$HOME/.local/bin" limelight -c "$YABAI_CONFIG_DIR/limelightrc" >> $HOME/.logs/limelight.log 2>> $HOME/.logs/limelight.err &

. "$YABAI_CONFIG_DIR/functions.sh"
. "$YABAI_CONFIG_DIR/rules.sh"

alias queryWindow="sleep 4; chunkc tiling::query --window \$(chunkc tiling::query --window id)"

# general space settings
yabai -m config layout                       bsp
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config insert_feedback_color   0xff$preselect_border_color

padding_size=10
yabai -m config window_gap                   18
yabai -m config top_padding                  $padding_size
yabai -m config bottom_padding               $padding_size
yabai -m config left_padding                 $padding_size
yabai -m config right_padding                $padding_size
unset padding_size

# floating windows are always on top (default: off)
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.2
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
# Only have win shadows for floating windows
yabai -m config window_shadow                float

yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise

yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

#
# NOTE: syntax for desktop-specific settings
#
# yabai -m config --space 5 layout float
