#!/bin/sh

if command -v gio > /dev/null; then
  for f in "$@"
  do
    gio trash -f "$f"
  done

elif command -v gvfs-trash > /dev/null; then
  for f in "$@"
  do
    gvfs-trash "$f"
  done

else
  if [ $OSTYPE = 'linux-gnu' ]; then
    TRASHDIR=${HOME}/.local/share/Trash/files
  elif [[ $OSTYPE =~ 'darwin' ]]; then
    TRASHDIR=${HOME}/.Trash
  fi
  for f in "$@"
  do
    mv "$f" "$TRASHDIR"
  done

fi
