#!/bin/sh

# provides shortcuts for git cloning
# git_clone() {
  if [[  "$1" =~ https://github.com ]] ; then
    git clone "$1"
  elif [[  "$1" =~ @github.com ]] ; then
    git clone "$1"
  elif [[  "$1" =~ github.com ]] ; then
    git clone https://"$1"
  else
    git clone https://github.com/"$1"
  fi
# }

