#!/bin/sh
# hist-search(){
  searchterm="$1"
  logs="$HOME"/.logs/shell-history-
  rg "$searchterm" "${logs}"* 2> /dev/null || \
    ag "${logs}"* "$searchterm" 2> /dev/null || \
    grep -r "$searchterm" "${logs}"*
  unset searchterm logs
# }
