#!/bin/sh
myEmacsC(){
    emacsclient --create-frame --alternate-editor='' -nw "$@"
}
# Use xterm-direct to convince doom emacs to use truecolor
if [ "$COLORTERM" = "truecolor" ]; then
    TERM=xterm-direct myEmacsC "$@"
else
    myEmacsC "$@"
fi
