#!/bin/sh
# Try to set vim to better versions.
# Will be expanded by functions, but not variables.

if command -v nvim >/dev/null 2>&1; then
  editor="nvim"
elif command -v mvim >/dev/null 2>&1; then
  # Prefer macvim to gvim.
  editor="mvim -v"
elif command -v gvim >/dev/null 2>&1; then
  editor="gvim -v"
elif [ -e /usr/bin/gvim ]; then
  editor="/usr/bin/gvim -v"
elif [ -e /usr/bin/vimx ]; then
  # xvim (has x11 clipboard support)
  editor="/usr/bin/vimx"
elif command -v vimx >/dev/null 2>&1; then
  editor="vimx"
elif command -v vim >/dev/null 2>&1; then
  editor="vim"
else
  # Old reliable caveman
  editor="vi"
fi

if [ "$1" = "--print-editor-only" ]; then
  echo "$editor"
else
  $editor "$@"
fi
