#!/bin/sh
set -eu
# nix-env -iA nixpkgs.$1 || nix-env -i $1

 # Check if an argument is provided
 if [ "$#" -ne 1 ]; then
     echo "Usage: $0 package-name"
     exit 1
 fi

 FILE="$HOME/.config/home-manager/local-packages.nix"

 # Insert the new package at the start of the list
 sed -i '/home.packages = with pkgs;\s*\[/a '"${1}" "$FILE"

 # Rerun home-manager install
 home-manager switch
