#!/bin/sh
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/../functions.sh"

# Delete and reclone current git directory
# reclone() {
  if is_git_repository ; then
    remoteUrl=$(git config --get remote.origin.url)
    repoFolder=$(pwd)
    cd .. && rm -rf "${repoFolder}" && git clone "${remoteUrl}" && cd "${repoFolder}"
  else
    echo "Error: not a git repository ${remoteUrl}"
    exit 1
  fi
# }

