#!/bin/sh
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/../functions.sh"

#TODO rceate function to try a range of terms...
# term() {
  terminals="
  kitty --single-instance -d $(pwd)
  gnome-terminal
  xfce4-terminal
  terminal
  iterm2
  wsl.exe
  "
  tarray=($terminals)
  for term in "${tarray[@]}" ; do
    # if [ $(function_exists "$browser") ]; then
    function_exists "$term"
    command -v $term >/dev/null 2>&1 # deliberately only get first word of cmd. Don't quote!
    if [ "$?" -eq 0 ]; then
      "$term" "$1"
      break
    fi
  done || echo "Terminal emulator unknown" >&2
# }
