#!/bin/sh
# vim_single_plugin(){
  plugin="$1"
  shift
  if [ -n "$2" ]; then
    editor="${2}"
    shift
  else
    editor="vim"
  fi
  "$editor" -u NORC --cmd "set rtp+=$HOME/.vim/plugins/$plugin" -c "nnoremap ; :" -c "nnoremap kv <esc>" $@
  unset plugin
# }
