#:schema https://docs.jj-vcs.dev/latest/config-schema.json
[aliases]
s = ["status"]
l = ["log"]
ol = ["op", "log"]
d = ["diff"]
bm = ["bookmark"]
rm = ["abandon"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
ignore = [
  'util', 'exec', '--', 'sh', '-c',
  'jj config set --repo snapshot.auto-track "$(jj config get snapshot.auto-track) & ~$0" && jj file untrack $0'
]

[ui]
default-command = ["status"]

[git]
# Never push commits like these
private-commits = "description('wip:*') | description('private:*')"

[merge-tools.diffview]
program = 'nvim'
merge-args = ['-n', '-c', 'DiffviewMergeFiles $output $base $left $right']
merge-tool-edits-conflict-markers = true
conflict-marker-style = 'git'
