# vim:ft=sh:tw=78:ts=2
# vim:foldmethod=marker:foldmarker={[},{]}
# Contains bash and cli bootstrapping/init code

# XXX For debugging, call $(bash_debug_log) with optional logfile param
# to show all bash commands run. Default logfile is ${HOME}/.debug_log_bashsetx.
# (More plusses mean different file/function)

# # If not running interactively, don't do anything
# case $- in
#     *i*) ;;
#       *) return;;
# esac
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# When changing shells, force setup again.
shell="$(ps -p $$ | tail -1 | awk '{print $NF}')"
if [ "$shell" != $(basename "$SHELL") ]; then
  unset PROFILE_LOADED
  export SHELL="$(which $shell)"
fi
if [ -z "$PROFILE_LOADED" ]; then
  source "${SCRIPT_DIR}/profile.sh"
fi

# Reload/source inputrc
# bind -f "${SCRIPT_DIR}/inputrc.sh"
# INPUTRC="${SCRIPT_DIR}/inputrc.sh"
source "${SCRIPT_DIR}/functions.sh"
source "${SCRIPT_DIR}/settings.sh"
BASH_ENV="${SCRIPT_DIR}/../aliases.sh" # Aliases are used for all readline apps.
source "${SCRIPT_DIR}/../aliases.sh"
alias_completion
source "${SCRIPT_DIR}/prompt/promptrc.sh"

# Unset include guards to allow refreshing
unset BASH_FUNCTIONS_LOADED SCRIPT_FUNCTIONS_LOADED

# Virtual console
if [ "$TERM" = "linux" ]; then
  # source "${DOTFILES_DIR}/terminal/virtual_console/reuse_X_colors.sh" "${DOTFILES_DIR}/terminal/x/solarized_light"
  source "${DOTFILES_DIR}/terminal/virtual_console/solarized_dark.sh"
fi
