# vim:ft=sh:tw=78:ts=2
# vim:foldmethod=marker:foldmarker={[},{]}
# Contains bash and cli bootstrapping/init code

# XXX For debugging, call $(bash_debug_log) with optional logfile param
# to show all bash commands run. Default logfile is ${HOME}/.debug_log_bashsetx.
# (More plusses mean different file/function)

# # If not running interactively, don't do anything
# case $- in
#     *i*) ;;
#       *) return;;
# esac
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${SCRIPT_DIR}/../XDG_setup.sh"
source "${SCRIPT_DIR}/../bootstrap_functions.sh"

loadProfile

# Reload/source inputrc
# bind -f "${SCRIPT_DIR}/inputrc.sh"
# INPUTRC="${SCRIPT_DIR}/inputrc.sh"
source "${SCRIPT_DIR}/functions.sh"
source "${SCRIPT_DIR}/settings.sh"
BASH_ENV="${SCRIPT_DIR}/../aliases.sh" # Aliases are used for all readline apps.
source "${SCRIPT_DIR}/../aliases.sh"
# 'have' is a command defined by bash completion. If it doesn't exist,
# completion isn't enabled.
if command -v have >/dev/null 2>&1 && [ "$LITE_SYSTEM" != 1 ]; then
  alias_completion
fi
source "${SCRIPT_DIR}/prompt/promptrc.sh"

# Unset include guards to allow refreshing
unset BASH_FUNCTIONS_LOADED SCRIPT_FUNCTIONS_LOADED

# Virtual console
if [ "$TERM" = "linux" ]; then
  # source "${DOTFILES_DIR}/terminal/virtual_console/reuse_X_colors.sh" "${DOTFILES_DIR}/terminal/x/solarized_light"
  source "${DOTFILES_DIR}/terminal/virtual_console/solarized_dark.sh"
fi
