
" set the cursor style when vim exits
" au VimLeave * set guicursor=a:block-blinkon0
if has('win32') || has ('win64')
    let $VIMHOME = $VIM."/vimfiles"
else
    let $VIMHOME = $HOME."/.vim"
endif
" let &runtimepath+=expand($VIMHOME)
" let &runtimepath+=expand($VIMHOME . "/after")
" let &runtimepath+=expand($VIMHOME . "/autoload")
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath

" let g:loaded_python_provider = 1
" let g:python_host_skip_check=1
" let g:python_host_prog = system('which python')
" let g:python3_host_skip_check=1
" let g:python3_host_prog = system('which python3')

source ~/.vimrc
