
" set the cursor style when vim exits
" au VimLeave * set guicursor=a:block-blinkon0
if has('win32') || has ('win64')
    let $VIMHOME = $HOME."/vimfiles"
else
    let $VIMHOME = $HOME."/.vim"
endif
" let &runtimepath+=expand($VIMHOME)
" let &runtimepath+=expand($VIMHOME . "/after")
" let &runtimepath+=expand($VIMHOME . "/autoload")
set runtimepath^=$VIMHOME runtimepath+=$VIMHOME/after
let &packpath=&runtimepath

" let g:loaded_python_provider = 1
" let g:python_host_skip_check=1
" let g:python_host_prog = system('which python')
" let g:python3_host_skip_check=1
" let g:python3_host_prog = system('which python3')


if has('win32') || has ('win64')
  if filereadable(expand("~/vimfiles/vimrc"))
    let s:vimrc="~/vimfiles/vimrc"
  else
    let s:vimrc="~/_vimrc"
  endif
else
  if filereadable(expand("~/.vim/vimrc"))
    let s:vimrc="~/.vim/vimrc"
  else
    let s:vimrc="~/.vimrc"
  endif
endif
exec "source " . s:vimrc
