# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

SCRIPT_DIR=${0:a:h}

# When changing shells, force setup again.
shell="$(ps -p $$ | tail -1 | awk '{print $NF}')"
if [ "$shell" != $(basename "$SHELL") ]; then
  unset PROFILE_LOADED
  export SHELL="$(which $shell)"
fi
if [ -z "$PROFILE_LOADED" ]; then
  source "${SCRIPT_DIR}/profile.zsh"
fi

source "${SCRIPT_DIR}/../aliases.sh"
source "${SCRIPT_DIR}/../variables.sh"
source "${SCRIPT_DIR}/functions.zsh"
# bindkey -v
source "${SCRIPT_DIR}/styles.zsh"
source "${SCRIPT_DIR}/settings.zsh"
source "${SCRIPT_DIR}/aliases_global.zsh"
source "${SCRIPT_DIR}/plugins.zsh"
source "${SCRIPT_DIR}/bindings.zsh"

# The following lines were added by compinstall
autoload -Uz compinit
compinit
# End of lines added by compinstall

