SCRIPT_DIR=${0:a:h}
source "${SCRIPT_DIR}/../XDG_setup.sh"
source "${SCRIPT_DIR}/../bootstrap_functions.sh"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

loadProfile

source "${SCRIPT_DIR}/../aliases.sh"
source "${SCRIPT_DIR}/functions.zsh"
source "${SCRIPT_DIR}/../variables.sh"
# bindkey -v
source "${SCRIPT_DIR}/styles.zsh"
source "${SCRIPT_DIR}/settings.zsh"
source "${SCRIPT_DIR}/aliases_global.zsh"
source "${SCRIPT_DIR}/plugins.zsh"
source "${SCRIPT_DIR}/bindings.zsh"

# Directory for custom completions
export ZSH_CUSTOM_COMPLETION_DIR="$XDG_DATA_HOME/zsh-completion"
DUMMY="$ZSH_CUSTOM_COMPLETION_DIR"/_dummy
mkdir -p "$ZSH_CUSTOM_COMPLETION_DIR"
fpath=($ZSH_CUSTOM_COMPLETION_DIR $fpath)

autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic
# The following lines were added by compinstall
autoload -Uz compinit
compinit
# End of lines added by compinstall
# Use bash completions as well when available?
autoload -Uz bashcompinit
bashcompinit

