#!/bin/sh
# vim: set tw=78 ts=4
# vim: foldmethod=marker foldmarker={[},{]}

export DOTFILES_DIR="$(cat $HOME/.config/.dotfiles_dir)"
X_DOTFILES_DIR="$DOTFILES_DIR"/system/x11

export DEFAULT_SESSION=bspwm
export COLOURSCHEME=ayu_light

. "$DOTFILES_DIR"/shell/XDG_setup.sh
. "$X_DOTFILES_DIR"/system_defaults.sh
. "$X_DOTFILES_DIR"/settings.sh

# Sometimes startx doesn't set up dbus stuff properly, apparently.
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval $(dbus-launch --exit-with-session --sh-syntax)
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
        dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# Will exec WM if in startx situation rather than managed session.
. "$X_DOTFILES_DIR"/programs.sh
