# -*-  mode: shell-script; -*-
# vim: set ft=sh:

# Removes carriage return characters.
function rmcr() {
    sed -i 's/\r$//' $1
}

# Replaces a file with the .bak version of itself.
function mkbak() {
    cp $1 $1.bak
}

function mkcd() {
    mkdir -p $1 && cd $1
}

alias cl="clear"
alias ..="cd .. && ls"
alias cd..="cd .. && ls"

alias ls="ls -F --color=auto"
alias lsa="ls -alF"
alias l='ls -CF'

alias gc="git clone"
alias open="nautilus $1 >/dev/null 2>&1"
alias :q="exit"

alias e="emacs -nw"
alias v="vim"

# Prevent files from being overwritten by redirection.
set -o noclobber
# Don't accidentally remove or overwrite files.
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

if [ -d "$HOME/.redis" ]; then
    alias redis="cd $HOME/.redis/redis-server"
fi

if [ -d "$HOME/workspace" ]; then
    alias ws="cd $HOME/workspace"
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


