# -*-  mode: shell-script; -*-
# vim: set ft=sh:

# XXX For debugging, `use set -x` to show all bash commands run.
# (More plusses mean different file/function)

# # If not running interactively, don't do anything
# case $- in
#     *i*) ;;
#       *) return;;
# esac

# # Run TMUX, close on exit.
#     { tmux attach || exec tmux new-session && exit;}
# fi
# Run tmux on connect
case $- in
    *i*)
    if command -v tmux>/dev/null; then
        if [[ ! $TERM =~ screen ]] && [[ -z $TMUX ]]; then
            PNAME="$(ps -o comm= $PPID)";
            if [ $PNAME == "login" ] || [ $PNAME == "sshd" ] || [ $PNAME == "gnome-terminal" ] ; then
                if tmux ls 2> /dev/null | grep -q -v attached; then
                    exec tmux attach -t $(tmux ls 2> /dev/null | grep -v attached | head -1 | cut -d : -f 1)
                else
                    exec tmux
                fi
            fi
        fi
    fi
    ;;
esac

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BASH_ENV="${SCRIPT_DIR}/aliases.sh" # Aliases are used for all readline apps.
source ${SCRIPT_DIR}/functions.sh
source ${SCRIPT_DIR}/aliases.sh
source ${SCRIPT_DIR}/prompt.sh
INPUTRC="${SCRIPT_DIR}/inputrc.sh"
