#! /bin/sh

export DOTFILES_DIR="$(cat $HOME/.config/.dotfiles_dir)" && \
pgrep sxhkd || sxhkd -m -1 -c "$HOME/.config/sxhkd/sxhkdrc" "$DOTFILES_DIR"/windowManagers/bspwm/*.sxhkd &

#  if [[ $(hostname) == 'myhost' ]]; then
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I

bspc_desktop(){
  i=2
  bspc monitor --add-desktops $i
}

gap=10

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap
bspc config top_padding $(($PANEL_HEIGHT-gap))

bspc config split_ratio          0.52
# Sets desktop layout to monocle if only one window
bspc config single monocle
bspc config borderless_monocle   true
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config paddingless monocle
bspc config auto_alternate true
bspc config focus_follows_pointer false
bspc config auto_cancel true
bspc config leaf_monocle true
bspc config adaptative_raise true
bspc config apply_floating_atom    true
bspc config history_aware_focus    true

# bspc config pointer_modifier super
# Don’t replay the click that makes a window focused.
bspc config swallow_first_click
# When focusing a window/monitor, put the pointer at its center.
bspc config pointer_follows_focus
bspc config pointer_follows_monito

bspc config border_width         7
# Unfocussed window
# bspc config normal_border_color "#332d29"
bspc config normal_border_color "#2101ad"
# Focused window in unfocused monitor
bspc config active_border_color "#2401bc"
# bspc config focused_border_color "#504339"
bspc config focused_border_color "#247dcc"
# bspc config presel_border_color "#9a875f"
bspc config presel_border_color "#d75f5f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
# Apparently overridden by compton
bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75
# Where to add new windows
bspc confic initial_polarity second_child


# Rules
bspc rule -a Skype pseudo_tiled=on
# bspc rule -a Spotify pseudo_tiled=on
# bspc rule -a Thunar pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# cratchpd
# You can emulate a dropdown terminal (like i3's scratchpad feature if you put a terminal in it) using bspwm's window flags. Append the following to the end of the bspwm config file (adapt to your own terminal emulator):

# bspc rule -a scratchpad sticky=on state=floating hidden=on
# st -c scratchpad -e ~/bin/scratch &
# The sticky flag ensures that the window is always present on the current desktop. And ~/bin/scratch is:

# #!/usr/bin/sh
# bspc query -N -n .floating > /tmp/scratchid
# $SHELL
# The hotkey for toggling the scratchpad should be bound to:

# id=$(cat /tmp/scratchid);\
# bspc node $id --flag hidden;bspc node -f $id

### Desktop where all windows are floating
 # change the desktop number here
 FLOATING_DESKTOP_ID=$(bspc query -D -d '^5')

 bspc subscribe node_manage | while read -a msg ; do
    desk_id=${msg[2]}
    wid=${msg[3]}
    [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
 done
