#! /bin/sh
exec 2> $HOME/.logs/bspwmrc.err
exec 1> $HOME/.logs/bspwmrc.log

export DOTFILES_DIR="$(cat $HOME/.config/.dotfiles_dir)"
# export DOTFILES_DIR="$(cat $HOME/.config/.dotfiles_dir)" && \
pgrep sxhkd || \
  sxhkd -m -1 -c "$HOME/.config/sxhkd/sxhkdrc" \
  "$DOTFILES_DIR"/windowManagers/bspwm/*.sxhkd \
   > $HOME/.logs/sxhkd.log 2> $HOME/.logs/sxhkd.err &
# flashfocus &

. "$DOTFILES_DIR"/windowManagers/bspwm/rules.sh

#  if [[ $(hostname) == 'myhost' ]]; then
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d " " " " " "

bspc_desktop(){
  i=2
  bspc monitor --add-desktops $i
}

gap=10
BSPWM_FOCUSED_COLOUR="#1cb5db" # Cyan
BSPWM_MODE_COLOUR="#00bc00" # dark-ish green
# bspc config focused_border_color "#247dcc" # dark blue
# bspc config focused_border_color "#00bcff" # simpler cyan

bsp_border_reset(){
  bspc config focused_border_color "$BSPWM_FOCUSED_COLOUR"
}

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap
bspc config top_padding $(($PANEL_HEIGHT-gap))
unset gap

bspc config split_ratio          0.52
# Sets desktop layout to monocle if only one window
bspc config single monocle
bspc config borderless_monocle   true
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config paddingless monocle
bspc config auto_alternate true
bspc config focus_follows_pointer true
bspc config auto_cancel true
bspc config leaf_monocle true
bspc config adaptative_raise true
bspc config apply_floating_atom    true
bspc config history_aware_focus    true

# Don’t replay the click that makes a window focused.
bspc config swallow_first_click true
# When focusing a window/monitor, put the pointer at its center.
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

bspc config pointer_modifier mod4 # super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config border_width         5
# currently unmerged PR. Not functional.
# bspc config border_radius         5
# Unfocussed window
# bspc config normal_border_color "#332d29"
bspc config normal_border_color "#2101ad"
# Focused window in unfocused monitor
bspc config active_border_color "#2401bc"
bspc config focused_border_color "$BSPWM_FOCUSED_COLOUR"
# bspc config presel_feedback_color "#9a875f"
bspc config presel_feedback_color "#d75f5f"
# Removed 0.9.1
# bspc config urgent_border_color "#9f7155"
# bspc config focused_locked_border_color "#9a875f"
# Apparently overridden by compton, not a valid option anyway.
bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75
# Where to add new windows
bspc config initial_polarity second_child


# cratchpd
# You can emulate a dropdown terminal (like i3's scratchpad feature if you put a terminal in it) using bspwm's window flags. Append the following to the end of the bspwm config file (adapt to your own terminal emulator):

# bspc rule -a scratchpad sticky=on state=floating hidden=on
# st -c scratchpad -e ~/bin/scratch &
# The sticky flag ensures that the window is always present on the current desktop. And ~/bin/scratch is:

# #!/usr/bin/sh
# bspc query -N -n .floating > /tmp/scratchid
# $SHELL
# The hotkey for toggling the scratchpad should be bound to:

# id=$(cat /tmp/scratchid);\
# bspc node $id --flag hidden;bspc node -f $id

### Desktop where all windows are floating
 # change the desktop number here
 FLOATING_DESKTOP_ID=$(bspc query -D -d '^5')

 bspc subscribe node_manage | while read -a msg ; do
    desk_id=${msg[2]}
    wid=${msg[3]}
    [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
 done
